### ISSUE TITLE
type error in 'qsort_small.c' (under 'automotive/qsort')

### ISSUE THREAD

**Issue by JOE1994** [embecosm/mibench#3]
Hello , 

I just wanted to mention that there is a type error at line 35 of `automotive/qsort/qsort_small.c`.
![image](https://user-images.githubusercontent.com/10286488/72670772-8f38b480-3a0f-11ea-97c3-fcb265efb2bf.png)

Weird thing is that the program still compiles successfully and gives the same output as the version whose type error at line 35 is fixed..

**Comment by jeremybennett** [comment]
@JOE1994 This is an issue with the original Mibench, of which this is just a copy. I suggest you raise it with the developers at the University of Michigan. Contact details at http://vhosts.eecs.umich.edu/mibench//
